name: check out project

on: [push]
jobs:
  list-file:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        id: list-file
        run: | # not checkout repo so this time cant see any files
          pwd
          ls 
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
      - name: log files
