name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
      max-parallel: 3
      # fail-fast: true
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}} # run node version 6 8 10 sequency
      - name: log node version
        run: node -v
